name: Build and Upload Artifacts

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Project
        run: |
          mkdir output
          echo "This is a build file" > output/hello.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-build-files
          path: output/
