name: Use Secrets Securely

on:
  workflow_dispatch:

jobs:
  use-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Print Secret (Bad Practice!)
        run: echo "${{ secrets.MY_SECRET }}"
